# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yu Sun
tagline:             "Stay hungry. Stay foolish."
description:         "Life was like a box of chocolates. You never know what you're gonna get."
url:                 "http://usunyu.com/" # the base hostname & protocol for your site
baseurl:             / # the subpath of your site, e.g. /blog/
# paginate:            5

# Subdirectory
# permalink:           /blog/:categories/:year/:month/:day/:title.html

# About/contact
author:
  name:              Yu Sun
  url:               https://www.facebook.com/yusun.io
  email:             usunyu@gmail.com

# Custom vars
version:             1.0.0
